### ISSUE TITLE
Implement Temporary Views

### ISSUE THREAD

**Issue by midhat** [helun/Ektorp#107]
Can we implement temporary views (Specified in http://wiki.apache.org/couchdb/HTTP_view_API#Temporary_Views) in ektorp.

**Comment by based2** [comment]
Should be closed (empty upper link) :

https://github.com/apache/couchdb/issues/932
"Sorry, temporary views are not coming back.

Have you considered using Mango selectors on _changes feeds? You'll get the same behaviour that you're looking for (one-time use filters), and the convenient output structure of a _changes feed which is easily parsed by your client code.

http://docs.couchdb.org/en/latest/api/database/changes.html#selector

The same syntax is supported for replication by specifying your selector directly in a _replicator document."
