### ISSUE TITLE
Problem deleting document

### ISSUE THREAD

**Issue by YochanaSH** [helun/Ektorp#200]
Hi There,

https://groups.google.com/forum/#!topic/ektorp-discuss/uLKl4bFph8Y
My code for delete document looks like this :

```
    Example ex = null;
    List<Example> res = findByExampleId(id);
    Iterator<Example> iterator = res.iterator();
    while (iterator.hasNext()) {
        ex = (Example)iterator.next();
    }
    db.delete(ex);
```

But it always fetches the older revision of the file resulting in org.ektorp.UpdateConflictException.

How do I fetch the latest revision to ensure the delete happens successfully ?

Many Thanks !

**Comment by YannRobert** [comment]
answered on groups
