### ISSUE TITLE
Current release (1.4.3) not available on Maven Central

### ISSUE THREAD

**Issue by DomiWag** [helun/Ektorp#234]
Hi,
I noticed that on GitHub, version 1.4.3 has been [officially released](https://github.com/helun/Ektorp/releases/tag/org.ektorp.parent-1.4.3) quite a while ago. However, [Maven Central](http://search.maven.org/#browse%7C-220502527) only has version 1.4.2.
Is there any chance you could fix this soon?
Thanks,
DomiWag

**Comment by sventorben** [comment]
Any chance of getting this released?

**Comment by bobsta** [comment]
@henrik is there anything I can do to help release 1.4.3 onto maven?

**Comment by henrik** [comment]
Wrong Henrik :) Good luck.

**Comment by YannRobert** [comment]
Version 1.4.4 was release on March 15th 2017, and is available on maven repository.
