### ISSUE TITLE
Function add problem

### ISSUE THREAD

**Issue by oumayma-ltaief** [helun/Ektorp#248]
Hello, 
I'm using Ektorp and I want to add a document. I wrote the bean like this:

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

public class CouchLightBean 
{
  @JsonIgnoreProperties({"_id", "_rev"})

  @JsonProperty("_id")
  private String id;

  @JsonProperty("_rev")
  private String rev;

  @JsonProperty("type")
  private String type;

 //and getter/setter
  }
Then with the CouchDbRepositorySupport I'm using the add function with the bean instanciation; I'm just setting "type" property, but I'm getting this error:

javax.servlet.ServletException: org.ektorp.DbAccessException: 400:Bad Request
URI: /sampledb/
Response Body: 
{
  "error" : "bad_request",
  "reason" : "Document id must be a string"
}
I guess this is due to not setting id and revision. How to fix this please?
Thanks.

**Comment by cberkeley** [comment]
Have you tried removing the JsonIgnoreProperties annotation? Also, I would recommend having your class extend ektorp's CouchDBDocument and removing the _id and rev members from your class. CouchDBDocument has setter/getters and some sanity checks as well.

**Comment by oumayma-ltaief** [comment]
the issue was resolved after removing @JsonProperty("_id") and @JsonProperty("_rev")
Thanks
