### ISSUE TITLE
using attachments from couchDB with ektorp

### ISSUE THREAD

**Issue by boxxxie** [helun/Ektorp#27]
I would be very interested to know how to use attachments with ektorp

I use this code:

MenuButtonHeader mb = db.get(MenuButtonHeader.class, doc);
System.out.println(mb.getAttachments());
Collection<Attachment> attachmentKeySet = mb.getAttachments().values();
Attachment att = null;
for(Attachment a : attachmentKeySet){
    att = a;
}
System.out.println(att.getContentLength());
System.out.println(att.getContentType());
System.out.println(att.getId());
System.out.println(att.isStub());

System.out.println(att.getDataBase64().length()); -----------> (NPE)

and get this output:
{menu-1.png=org.ektorp.Attachment@69d6065}
2094
image/png
null
true

The ID of my attachment is null, and the data DataBase64 is null.
I've read the documentation from http://www.ektorp.org/reference_documentation.html#d0e909 but it hasn't been able to help me solve my problem of loading an attachment from couchdb into java.

thanks

**Comment by Harshita-coder** [comment]
Hello ,

I am not able to get the content of the attachment.

while creating an attachment (Spring boot ektorp)

byte[] fileInBytes = FileUtils.readFileToByteArray(file);
		String base64EncodedData = java.util.Base64.getEncoder().encodeToString(fileInBytes);
		Attachment inline = new Attachment(fileName, base64EncodedData, "application/pdf");
		regDocument.addInlineAttachment(inline);
		regDocumentRepository.add(regDocument);

--------------------------------------------------------------------------

@Data
@EqualsAndHashCode(onlyExplicitlyIncluded = true, callSuper = true)
@NoArgsConstructor
@TypeDiscriminator("doc.type === 'RegistrationDocument'")
public class RegistrationDocument extends CouchDbDocument {
	
	 private static final long serialVersionUID = 1L;
	
	 private String bnr12;
	 
     private String pfad;
     
     private File pdfdocument;
     
     private String type;
     
     private String createdOn;
     
     @Override
     public void addInlineAttachment(Attachment a) {
    	 super.addInlineAttachment(a);
     }

}
----------------------------------------------------------------------
@Repository
@Lazy
public class RegistrationDocumentRepository extends CouchDbRepositorySupport<RegistrationDocument> {

	 @Qualifier("couchDbConnector")
	 private CouchDbConnector couchDbConnector;
	 
	 public RegistrationDocumentRepository(CouchDbConnector couchDbConnector) {
		super(RegistrationDocument.class, couchDbConnector);
		//initStandardDesignDocument();
		// TODO Auto-generated constructor stub
	}

	 /*@GenerateView @Override
     public List<RegistrationDocument> getAll() {
             ViewQuery q = createQuery("all").descending(true);
             return db.queryView(q, RegistrationDocument.class);
     }*/
	
}

Attachment data = registrationDocument.getAttachments().get(key);

I see the file attachment in db also i am getting the name, size but not able to get the content.
Please advise!
