### ISSUE TITLE
Changes feed stopped

### ISSUE THREAD

**Issue by oumayma-ltaief** [helun/Ektorp#276]
Hello I am using Ektorp in my Java app and I have created a thread listening changes on CouchDB; it was working till I get this message on log : "Changes feed stopped. Reason: EOF"
What does EOF refer to ? How to fix this issue please?

**Comment by YannRobert** [comment]
Hi @oumayma-ltaief , 
An application should assume IO errors can occur anytime when using the network. 
So to be resilient, your thread should handle such errors, most of the time by just restarting a new request to listen to changes when the previous one failed. 
You just have to check the rate of errors is not too high, but if it occurs only once in a while, this should be ok.
