### ISSUE TITLE
LocalDateTime fields serializes as a nested document, but fails to de-serialize back

### ISSUE THREAD

**Issue by graynk** [helun/Ektorp#284]
My class (extended from CouchDbDocument) contains LocalDateTime field. When I save it through the repository it saves like this:
```
... some fields...
"date": {
    "second": 11,
    "hour": 17,
    "minute": 21,
    "nano": 661000000,
    "year": 2018,
    "monthValue": 8,
    "month": "AUGUST",
    "dayOfMonth": 14,
    "dayOfYear": 226,
    "dayOfWeek": "TUESDAY",
    "chronology": {
      "calendarType": "iso8601",
      "id": "ISO"
    }
  }
...other fields...
```
However, when I try to de-serialize the document back, I get an exception:

> org.ektorp.DbAccessException: com.fasterxml.jackson.databind.JsonMappingException: No suitable constructor found for type [simple type, class java.time.LocalDateTime]: can not instantiate from JSON object (missing default constructor or creator, or perhaps need to add/enable type information?)
 at [Source: N/A; line: -1, column: -1] (through reference chain: model.HemaAnalysis["date"])

Do I provide my own ObjectMapper? Do I use [jackson-modules-java8](https://github.com/FasterXML/jackson-modules-java8)? Do I add another constructor? This is not documented anywhere as far as I can tell.

**Comment by YannRobert** [comment]
This is not an issue on Ektorp.

This is a Jackson usage issue.
Please see https://stackoverflow.com/questions/27952472/serialize-deserialize-java-8-java-time-with-jackson-json-mapper
