### ISSUE TITLE
Dependency Conflict: duplicate classes "org.apache.commons.logging.LogFactory" in different JARs, have different implementations. 

### ISSUE THREAD

**Issue by HelloCoCooo** [helun/Ektorp#293]
Hi, in **org.ektorp.parent-1.5.0**, duplicate classes with the same fully-qualified name **org.apache.commons.logging.LogFactory** are included in two different libraries, i.e., **org.slf4j:jcl-over-slf4j:1.6.4** and **commons-logging:commons-logging:1.1.1**. 

According to _"first declaration wins"_ class loading strategy, only the class in **org.slf4j:jcl-over-slf4j:1.6.4** can be loaded, and that in **commons-logging:commons-logging:1.1.1** will be shadowed.

By further analyzing, your project expects to invoke method **<org.apache.commons.logging.LogFactory: org.apache.commons.logging.LogFactory getFactory()>** in **commons-logging:commons-logging:1.1.1**. As it has been shadowed, so that this method defined in **org.slf4j:jcl-over-slf4j:1.6.4** is actually forced to be referenced via the following invocation path:

```
<org.ektorp.android.http.AndroidHttpClient$Builder: org.apache.http.conn.ClientConnectionManager configureConnectionManager(org.apache.http.params.HttpParams)> D:\testcase\TestProject\Ektorp-org.ektorp.parent-1.5.0\org.ektorp.android\target\classes
<org.apache.http.impl.conn.tsccm.ThreadSafeClientConnManager: void <init>(org.apache.http.params.HttpParams,org.apache.http.conn.scheme.SchemeRegistry)> D:\cEnvironment\repository\org\apache\httpcomponents\httpclient\4.3\httpclient-4.3.jar
<org.apache.commons.logging.LogFactory: org.apache.commons.logging.Log getLog(java.lang.Class)>
<org.apache.commons.logging.LogFactory: org.apache.commons.logging.LogFactory getFactory()>

```

Although both of these two conflicting classes contain the referenced method (with the same signature), they have completely different implementations. This issue will not lead to runtime crashes, but it can introduce inconsistent semantic hehavior by changing the control flows and data flows.

### Solution:

Reverse the declaration order of **org.slf4j:jcl-over-slf4j:1.6.4** and **commons-logging:commons-logging:1.1.1** in pom.xml.
Then, according to "first declaration wins" class loading strategy, class org.apache.commons.logging.LogFactory in commons-logging:commons-logging:1.1.1 can be loaded (the version s3-wagon-private expects to reference by static analysis).

This fix will not affect other libraries or class, except the above duplicate class.

**Dependency tree-----**
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ org.ektorp.android ---
[INFO] org.ektorp:org.ektorp.android:jar:1.5.0
[INFO] +- org.ektorp:org.ektorp:jar:1.5.0:compile
[INFO] |  +- org.apache.httpcomponents:httpclient:jar:4.3:compile
[INFO] |  |  +- org.apache.httpcomponents:httpcore:jar:4.3:compile
[INFO] |  |  \- commons-codec:commons-codec:jar:1.6:compile
[INFO] |  +- org.apache.httpcomponents:httpclient-cache:jar:4.3:compile
[INFO] |  |  \- (org.apache.httpcomponents:httpclient:jar:4.3:compile - omitted for duplicate)
[INFO] |  +- commons-io:commons-io:jar:2.0.1:compile
[INFO] |  +- org.slf4j:slf4j-api:jar:1.6.4:compile
[INFO] |  +- _**org.slf4j:jcl-over-slf4j:jar:1.6.4:runtime**_
[INFO] |  |  \- (org.slf4j:slf4j-api:jar:1.6.4:runtime - omitted for duplicate)
[INFO] |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.6.7:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-core:jar:2.6.7:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.6.7:compile
[INFO] |  |  +- (com.fasterxml.jackson.core:jackson-annotations:jar:2.6.7:compile - version managed from 2.6.0; omitted for duplicate)
[INFO] |  |  \- (com.fasterxml.jackson.core:jackson-core:jar:2.6.7:compile - omitted for duplicate)
[INFO] |  \- (net.sourceforge.findbugs:annotations:jar:1.3.2:compile - omitted for duplicate)
[INFO] +- com.google.android:android:jar:4.0.1.2:provided
[INFO] |  +- _**commons-logging:commons-logging:jar:1.1.1:provided**_
[INFO] |  +- (org.apache.httpcomponents:httpclient:jar:4.0.1:provided - omitted for conflict with 4.3)
[INFO] |  +- org.khronos:opengl-api:jar:gl1.1-android-2.1_r1:provided
[INFO] |  +- xerces:xmlParserAPIs:jar:2.6.2:provided
[INFO] |  +- xpp3:xpp3:jar:1.1.4c:provided
[INFO] |  \- org.json:json:jar:20080701:provided
[INFO] +- org.mockito:mockito-all:jar:1.8.5:test
[INFO] +- junit:junit:jar:4.8.2:test
[INFO] \- net.sourceforge.findbugs:annotations:jar:1.3.2:compile

Thanks!
Best regards,
Coco

**Comment by HelloCoCooo** [comment]
Code snippet of <org.apache.commons.logging.LogFactory: org.apache.commons.logging.LogFactory getFactory()> in org.slf4j:jcl-over-slf4j:jar:1.6.4 (loaded version):
![01](https://user-images.githubusercontent.com/46306510/55473747-04cec200-5642-11e9-878c-6639cffbb2e6.png)


Code snippet of <org.apache.commons.logging.LogFactory: org.apache.commons.logging.LogFactory getFactory()> in commons-logging:commons-logging:1.1.1 (shadowed but expected to invoke method):
![02](https://user-images.githubusercontent.com/46306510/55473755-09937600-5642-11e9-8f9a-1b41297f70c9.png)
....

As a result, method this conflicting method included in commons-logging:commons-logging:1.1.3 deals with completely different cases, which changes the control flows and data flows. So being forced to use this method in org.slf4j:jcl-over-slf4j:jar:1.6.4 may lead to inconsisitent semantic behaviors.

**Comment by HelloCoCooo** [comment]
@helun May I pull a request to fix it? 8)

Thanks again.

**Comment by HelloCoCooo** [comment]
Using the following test case to run on these two versions of methods separately starting from the entry method **field.get(clientConnectionManager);_** in your project, then we can find that the return values of this entry method is assigned different values.
[TestcaseforhelunEktorp.txt](https://github.com/helun/Ektorp/files/3105670/TestcaseforhelunEktorp.txt)



Please check whether the changes of this variable value will affect your semantic behaviors.

**Comment by rayzhang0603** [comment]
@HelloCoCooo you should @ the developer of this project :)

**Comment by HelloCoCooo** [comment]
@rayzhang0603 Sorry for that...

**Comment by YannRobert** [comment]
Hi @HelloCoCooo 

Maybe I did not understand. If so please tell me.

It seem to me that your issue is related to your runtime classpath.
I don't get why it needs to be fixed in Ektorp.

Only you can control your application classpath.
If your application classpath somehow depends on maven dependencies, you should be able to exclude whatever you dislike, or even reorder them.

I hope this helps.

**Comment by HelloCoCooo** [comment]
@YannRobert 
Thanks for your quick reply.
These two libraries (**_org.slf4j:jcl-over-slf4j:1.6.4_** and **_commons-logging:commons-logging:1.1.1_**) containing conflicting classes are introduced by **_Ektorp_**, we can  control our own application classpath, but I cannot revise **_Ektorp_**'s dependencies.

As in **_Ektorp_** ,  **_httpcomponents_**  depends on **_commons-logging_** rather than **_org.slf4j:jcl-over-slf4j_**, when **_httpcomponents_** is forced to reference to the class **_org.apache.commons.logging.LogFactory_** in **_org.slf4j:jcl-over-slf4j:1.6.4_** due to dependency conflicts (first declaration wins), the code hehaviors will change.

So maybe the better solution is to reverse the declaration order in **_Ektorp's_** pom file.

May I submit a PR to fix this problem?
This fix will not affect other libraries or classes.

Thanks again.
Best, 
Coco

**Comment by YannRobert** [comment]
Sure, you can submit a PR.
Maybe your PR will help to understand.

But please try to change your own project, exclude any transitive dependencies about logging from Ektorp, and include the depencencies you want instead.

I am still not convince that this is an issue that concerns Ektorp build.

**Comment by HelloCoCooo** [comment]
@YannRobert Ok. I understand.
Maybe the semantic hehavior changes are not harmful to Ektorp.

Then I can close this issue.
Thank you.

**Comment by HelloCoCooo** [comment]
@YannRobert 
Hi,  lots of issues are caused by this conflicting class:

https://github.com/search?p=3&q=org.apache.commons.logging.LogFactory&type=Issues

If you discover unexpected code behaviors due to such conflicting class, feel free to reopen this issue,
I still happy to fix it.
