### ISSUE TITLE
How to retrieve documents when a field is not present in some of them

### ISSUE THREAD

**Issue by aashirwadgupta** [helun/Ektorp#294]
Hi Team, 
We recently ran into a case wherein we have to add two extra fields in our documents. But the documents which were previously under that database will not be having these two fields. 
I am now not able to create the viewquery which fetches me the data where the old and new documents should get fetched even when I use a condition applicable for new ones. 

*For Ex*
Suppose we had an Employee Document
```
{
_id
_rev
fName
lName
department
}
```

Now this is modified by two fields
```
{
_id
_rev
fName
lName
department
isManager -- boolean
managerId -- String
}
```

What should be my approach to write view query to fetch employees who are manager? Considering that the previous employees should also get fetched.

**Comment by YannRobert** [comment]
This is a CouchDB question that is not specific to Ektorp.
Please use CouchDB documentation.

Just be careful not so use primitive types in you domain model, so that you get null value when the field is not set in the Document.
