### ISSUE TITLE
org.ektorp.UpdateConflictException: document update conflict: id: unknown rev: unknown

### ISSUE THREAD

**Issue by nestoru** [helun/Ektorp#49]
Hi,

Is the 'unknown' below a bug or is there a way to return the conflicting id/rev?

org.ektorp.UpdateConflictException: document update conflict: id: unknown rev: unknown

Thanks,
-Nestor

**Comment by swedhaselva** [comment]
hey helun...
_id:"12314"
_rev id:"1-35637877878899yeye"
userId:"swe123"
age:"45"
this is my fields...but when i try to create a document with attachments...only id ,rev id and attachment id is being created...not other fields of my documents

**Comment by claritysoftwaregroup** [comment]
Could you please provide some steps to replicate this? I can't pinpoint what is causing this issue in our system
