### ISSUE TITLE
the first query always fails after a CouchDbConnector created

### ISSUE THREAD

**Issue by yblee85** [helun/Ektorp#91]
I'm using ektorp-1.2.1.

I created a dbInstacne and using several CouchDbConnectors with this CouchDbInstance.

for the first few times, it works fine. 
but at one point, the first query fails after a CouchDbConnector created.

here's the code summary

---

HttpClient httpClient = new StdHttpClient.Builder().connectionTimeout(0).socketTimeout(0).url(address).build();

CouchDbInstance dbInstance = new StdCouchDbInstance(httpClient);

CouchDbConnector dbCon = new StdCouchDbConnector("db_A", dbInstance);
//using dbCon for query.... (it works)

dbCon = new StdCouchDbConnector("db_B", dbInstance);
//using dbCon for query.... (it works)

dbCon = new StdCouchDbConnector("db_C", dbInstance);
//using dbCon for query.... (it works)

// i used same dbCon value as different connectors with a same dbInstance.

//FIXME : at some point, it won't work
dbCon = new StdCouchDbConnector("db_A", dbInstance);
ViewQuery query = new ViewQuery().designDocId("_design/A").viewName("viewName_A").key("keyA");
try {
ViewResult result = dbCon.queryView(query); // it throws an "SocketTimeoutException: Read timed out" exception.
} catch(Exception e){}

ViewResult result = dbCon.queryView(query); // now it works...

---

should i created different CouchDbInstance for different db?
or is this a bug?

**Comment by aashirwadgupta** [comment]
Even we are facing timeout errors post increasing timeout to 12000 milliseconds, and to the extent of 900000 milliseconds. 
This happens when we upload an attachment to db object and then try to get the data. 

P.S. our application is deployed on Azure and there exists a load balancer at couchDB
